import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@radix-ui/themes/styles.css";
import "../globals.css";
import Link from "next/link";
import { CameraIcon, GridIcon, HomeIcon, LayoutGrid, SearchIcon, User } from "lucide-react";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}>
        <Theme>
          {children}
          <div className="fixed right-0 bottom-0 left-0 bg-white px-4 py-2">
            <div className="max-w-lg mx-auto flex justify-between text-gray-500 *:size-12 *:flex *:items-center *:justify-center">
              <Link href="/">
                <HomeIcon/>
              </Link>
              <Link href="/profile">
                <SearchIcon/>
              </Link>
              <Link 
                href="/create" 
                className="flex items-center justify-center bg-gradient-to-tr from-orange-600 to-rose-500 p-4 size-12 text-white rounded-full">
                <CameraIcon/>
              </Link>
              <Link href="/browse">
                <LayoutGrid/>
              </Link>
              <Link href="/profile" className="">
                <User/>
              </Link>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
